### ISSUE TITLE
[BUG] form elements icons are not clickable (list)

### ISSUE THREAD

**Issue by haizenbergD** [formio/angular#626] opened 2020-09-26 13:23 UTC
Hi all.
I am facing with an issue while trying to work with form io items.
For some reasons some of the items in the list have non-clickable buttons which appears on element hover (edit, remove, edit json etc.)
At the same time icons itself displayed (not a bootstrap issue)

This happens only if I am passing data to form builder as json data.

```
    "angular-formio": "^4.11.0",
    "@angular/animations": "~9.1.6",
    "@angular/common": "~9.1.6",
    "@angular/compiler": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/elements": "^9.1.11",
    "@angular/forms": "~9.1.6",
    "@angular/localize": "^9.1.11",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
```
Please let me know if any additional information required.
Thanks

**Comment by travist** [comment] 2020-09-28 14:56
Will you please work up a live example so that we can see the issue ourselves instead of trying to setup a reproducible case?

**Comment by haizenbergD** [comment] 2020-09-28 16:18
@travist thanks for the reply!
I was trying to create an example where you can see an issue but no luck.
Actually my form is simple 
```
  <form-builder [form]="form" (change)="onChange($event)"></form-builder>
```
Form is object with a components property (array)

One interesting thing it that for items I have issue I see no tooltip text while hover mouse on edit, edit json, remove buttons in the list. 

Maybe you can give me some advices why some items may have an issue?

**Comment by haizenbergD** [comment] 2020-09-28 17:03
In addition I found that there are no event listeners added to the buttons which have an issue.

**Comment by haizenbergD** [comment] 2020-09-28 17:52
If there are any ways to force form-builder redraw form items?

**Comment by travist** [comment] 2020-09-29 20:39
We are not able to reproduce. Please provide a live example.

**Comment by daneformio** [comment] 2024-01-31 14:53
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-01-31 14:53 UTC
