### ISSUE TITLE
[FEATURE] Nativescript Support

### ISSUE THREAD

**Issue by sayanamanikanta** [formio/angular#536] opened 2020-05-07 06:34 UTC
When i try to use the form io in my native script mobile application it's not working. it trowing the exception 

> JS: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "./../../buffer/index.js", relative to: app/

Is formio will work with native script? Can any one help do i need to install any dependency.
I have already installed bellow packages

"@angular/elements": "^9.1.4",
"angular-formio": "^4.7.9",
"bootstrap": "^4.4.1",

am i forgot any thing to install

**Comment by travist** [comment] 2020-05-07 14:33
We currently do not support NativeScript, so moving this to a Feature request.

**Comment by sayanamanikanta** [comment] 2020-05-08 04:11
> We currently do not support NativeScript, so moving this to a Feature request.

is it possible to use at least the rendered feature of formio in NativeScript?

**Comment by travist** [comment] 2020-05-08 14:58
I honestly don't know. I have not tried it and we currently do not have the bandwidth to support it moving forward. You will need the community to chime in here on this one.

**Comment by sayanamanikanta** [comment] 2020-05-11 05:31
Ho Okay. Thanks!

**Comment by Sidiro23** [comment] 2024-02-07 14:58
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-02-07 14:58 UTC
Labels: enhancement
