### ISSUE TITLE
DataGrid refreshon on value change not working[Bug]

### ISSUE THREAD

**Issue by naveen4854** [formio/angular#311] opened 2019-06-17 14:31 UTC
I am trying to create a data table custom component, which has a edit display with a text input and a datagrid, which shows certain data based on data entered in text input 
```js
{
    weight: 0,
    type: 'textfield',
    input: true,
    key: 'apiUrl',
    label: 'Data Source Url',
    placeholder: 'Data Source Url',
    tooltip: 'Data Source Url.',
    validate: {
      required: true
    },
  },
  {
    type: 'datagrid',
    input: true,
    label: '',
    key: 'columns',
    tooltip: 'Values to use as the data source. Labels are shown in the select field. Values are the corresponding values saved with the submission.',
    weight: 10,
    reorder: true,
    refreshOn: 'apiUrl',
    disableAddingRemovingRows: true,
    refreshButton : true,
    components: [
      {
        label: 'Columns',
        key: 'label',
        input: true,
        type: 'textfield',
        disabled: true,
        refreshOn: 'apiUrl',
      },
      {
        label: 'Display',
        hideLabel: true,
        key: 'value',
        input: true,
        type: 'checkbox',
        allowCalculateOverride: true,
        refreshOn: 'apiUrl',
        // calculateValue: { _camelCase: [{ var: 'row.label' }] }
      }
    ],
    //"customConditional": "show = !!showColumns"
  }
```

so that datagrid is suppose to refresh on change event of the input box, 

but i dont see any changes, but when i actually click on add another button... all the rows show up with one more new row. 

please help me out if i am misunderstanding refreshon here or guide me on what am i missing

**Comment by imshivamchauhan** [comment] 2019-07-19 06:07
any update on this?

**Comment by naveen4854** [comment] 2019-07-23 07:18
nope!! looks like no one is even looking into this

**Comment by travist** [comment] 2019-07-24 16:00
We do have an eye on this, but have an active backlog that is keeping us busy. If this is blocking you, then we do have an option to pay to expedite this feature since this is not a critical item for our team to investigate at the moment. Also, please keep in mind that this whole library is Open Source and you have the ability to debug it and fix the issue yourself.  

Please let me know if you would like to expedite the resolution and we can assign this to our developers as a High priority bug fix.

**Comment by lane-formio** [comment] 2024-01-31 14:49
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by lane-formio** 2024-01-31 14:49 UTC
