### ISSUE TITLE
[BUG] Invalid attempt to spread non-iterable instance when populating tree component

### ISSUE THREAD

**Issue by StefanRupertsberger** [formio/angular#719] opened 2021-02-15 13:43 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:

`angular-formio@v4.11.4`

- Frontend framework:

`Angular v7.2.4`

- Browser:

Chrome, Firefox, Edge

- Browser version: 88.0.4324.150

## Steps to Reproduce
1. Create Tree Component
2. Drag another component into tree
3. Get error

## Expected behavior

Dragging component into tree component, it should be added

## Observed behavior

The component does not get added and I get the following error:

```
Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableSpread (WebformBuilder.js:88)
    at _toConsumableArray (WebformBuilder.js:86)
    at WebformBuilder.findNamespaceRoot (WebformBuilder.js:601)
    at WebformBuilder.onDrop (WebformBuilder.js:1003)
    at Object.<anonymous> (WebformBuilder.js:831)
    at emitter (dragula.js:714)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (dragula.js:713)
    at Object.thing.emit (dragula.js:705)
    at drop (dragula.js:301)
```

Before adding the JSON of the tree looks like this:

```
components: []
input: true
key: "tree"
label: "Tree"
tableView: false
type: "tree"
```

When I open the dialog to edit the component, save it without doing anything it works as expected... (JSON does not change).

**Comment by StefanRupertsberger** [comment] 2021-02-15 13:53
Same thing happens with angular-formio@v4.11.2

**Comment by wag110894** [comment] 2021-02-19 16:47
Hello @StefanRupertsberger,

We are not experiencing any issues on our side using Formiojs: 4.13.0-rc.4. Can you test using the Angular-formio equivalent, which is v4.12.0-rc.3?

**Comment by StefanRupertsberger** [comment] 2021-02-22 06:24
Tried it and that version does not work at all... I can't even add a nomal textfield:

```
Uncaught TypeError: Cannot read property 'component' of null
    at WebformBuilder.saveComponent (WebformBuilder.js:1446)
    at HTMLButtonElement.<anonymous> (WebformBuilder.js:1654)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
    at invokeTask (zone.js:1744)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1770)
```

**Comment by travist** [comment] 2021-02-22 15:34
There has been some recent changes to the Tree component pulled into the 4.13.0-rc.11 version. Can you try that version and see if it is any better?

**Comment by StefanRupertsberger** [comment] 2021-02-23 05:36
There is no such version for the package `angular-formio`. The newest one is `4.12.0-rc.3` and this one does not work.

**Comment by travist** [comment] 2021-02-23 22:08
Ok, we will need to upgrade that version.

**Comment by StefanRupertsberger** [comment] 2021-02-25 06:46
Ok, would be great if that fixes it.

**Comment by StefanRupertsberger** [comment] 2021-03-25 13:52
Are there any updates on this problem?

**Comment by wag110894** [comment] 2021-04-01 16:10
Hello @StefanRupertsberger, 

We have this item is currently assigned to a developer. We will let you know once this has been resolved.

**Comment by Sidiro23** [comment] 2024-02-14 14:17
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-02-14 14:17 UTC
Labels: bug
