### ISSUE TITLE
NPM install error in dependency tree

### ISSUE THREAD

**Issue by weilies** [formio/angular#737] opened 2021-03-08 04:03 UTC
I am getting error
```
chok@cloudshell:~/apps/my-app (fx-vps-225216)$ npm install --save angular-formio
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.0.0
npm ERR! Found: @angular/common@11.2.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.2.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0" from angular-formio@4.11.4
npm ERR! node_modules/angular-formio
npm ERR!   angular-formio@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/weilies_chok/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/weilies_chok/.npm/_logs/2021-03-08T04_01_26_030Z-debug.log
weilies_chok@cloudshell:~/apps/my-app (fx-vps-225216)$
```
Then i tried add --legacy-peer-deps, it fixed the issue. But after that, the audit fix get bunch of error again...

eilies_chok@cloudshell:~/apps/my-app (fx-vps-225216)$ npm audit fix
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.0.0
npm ERR! Found: @angular/common@11.2.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.2.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0" from angular-formio@4.11.4
npm ERR! node_modules/angular-formio
npm ERR!   angular-formio@"^4.11.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/weilies_chok/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/weilies_chok/.npm/_logs/2021-03-08T04_04_53_665Z-debug.log
weilies_chok@cloudshell:~/apps/my-app (fx-vps-225216)$

Anyone have luck to make it work? Appreciated for any helps~

**Comment by mukeshmjn** [comment] 2021-03-19 15:45
Assign this to me . When you are doing npm install then you getting this error right?

**Comment by sir-wally** [comment] 2021-04-22 20:09
getting the same error via npm install node v15.13.0

**Comment by weilies** [comment] 2021-04-23 00:14
Sorry for late reply. Yes @mukeshmjn end up I have to completely stop using this feature. Let me know if it's fixed so I can proceed. Thanks

**Comment by sir-wally** [comment] 2021-04-23 01:19
@weilies can you assign it to him? might help it getting it fixed. I ended up having to downgrade angularcli and adding --legacy-peer-deps to get it working

**Comment by weilies** [comment] 2021-04-23 01:59
@sir-wally how to assign to someone? Probably the owner of this repo can help. I have changed the direction and wont use it for the moment.

**Comment by mukeshmjn** [comment] 2021-04-23 01:59
Yes @weilies assign it to him

**Comment by weilies** [comment] 2021-04-23 02:03
@mukeshmjn  i can only perform the "@" mention, not sure how to assign. sorry bout that

**Comment by mukeshmjn** [comment] 2021-04-23 02:11
@weilies there must be an assign button

**Comment by weilies** [comment] 2021-04-23 02:22
![image](https://user-images.githubusercontent.com/484828/115808883-b43f8280-a41d-11eb-8850-2056aead2149.png)
yes, bu it's a LABEL, not an editable field :(

**Comment by mukeshmjn** [comment] 2021-04-23 02:24
I guess only the owner Of repo can do this..

**Comment by weilies** [comment] 2021-04-23 02:38
i will jz leave it there then :)

**Comment by sir-wally** [comment] 2021-04-23 15:43
@mukeshmjn what version of angular does form.io officially support? I can't seem to find any documentation on that

**Comment by mukeshmjn** [comment] 2021-04-23 15:44
I think they support all versions?

**Comment by weilies** [comment] 2021-09-21 00:42
hi all, is this fixed? i am still getting this TODAY... :(

**Comment by lane-formio** [comment] 2024-02-07 14:34
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by lane-formio** 2024-02-07 14:34 UTC
Labels: question
