### ISSUE TITLE
getting error at the time of gulp build ('ngc' errored after 59 ms)

### ISSUE THREAD

**Issue by pooja-waikar** [formio/angular#619] opened 2020-09-07 12:45 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 4.10.0-rc.5
- Formio.js version:^4.12.0-rc.13
- Frontend framework: angular 
- Browser: chrome
- Browser version:

## Steps to Reproduce
1. git clone https://github.com/formio/angular-formio.git
2. npm install
3. gulp build

## Expected behavior
project should get build properly
## Observed behavior
[17:41:33] Starting 'build'...
[17:41:33] Starting 'clean'...
[17:41:33] Starting 'clean:dist'...
[17:41:33] Starting 'clean:tmp'...
[17:41:33] Starting 'clean:build'...
[17:41:33] Finished 'clean:dist' after 2.56 ms
[17:41:33] Finished 'clean:build' after 3.44 ms
[17:41:33] Finished 'clean:tmp' after 21 ms
[17:41:33] Finished 'clean' after 22 ms
[17:41:33] Starting 'compile'...
[17:41:33] Starting 'clean:dist'...
[17:41:33] Finished 'clean:dist' after 226 μs
[17:41:33] Starting 'copy:source'...
[17:41:33] Finished 'copy:source' after 213 ms
[17:41:33] Starting 'formio:all'...
[17:41:33] Starting 'styles-formio'...
[17:41:33] Starting 'styles-builder'...
[17:41:33] Starting 'formio-css'...
[17:41:33] Starting 'builder-css'...
[17:41:34] Finished 'formio-css' after 247 ms
[17:41:34] Finished 'styles-builder' after 248 ms
[17:41:34] Finished 'builder-css' after 248 ms
[17:41:34] Finished 'styles-formio' after 249 ms
[17:41:34] Finished 'formio:all' after 249 ms
[17:41:34] Starting 'inline-resources'...
[17:41:34] Finished 'inline-resources' after 41 ms
[17:41:34] Starting 'ngc:all'...
[17:41:34] Starting 'ngc'...
[17:41:34] Starting 'ngc-angular'...
[17:41:34] Starting 'ngc-auth'...
[17:41:34] Starting 'ngc-auth-angular'...
[17:41:34] Starting 'ngc-manager'...
[17:41:34] Starting 'ngc-manager-angular'...
[17:41:34] Starting 'ngc-grid'...
[17:41:34] Starting 'ngc-grid-angular'...
[17:41:34] Starting 'ngc-resource'...
[17:41:34] Starting 'ngc-resource-angular'...
[17:41:34] 'ngc' errored after 59 ms
[17:41:34] Error: spawn ngc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[17:41:34] 'ngc:all' errored after 60 ms
[17:41:34] 'compile' errored after 565 ms
[17:41:34] 'build' errored after 589 ms
[17:41:34] The following tasks did not complete: ngc-angular, ngc-auth, ngc-auth-angular, ngc-manager, ngc-manager-angular, ngc-grid, ngc-grid-angular, ngc-resource, ngc-resource-angular
[17:41:34] Did you forget to signal async completion?

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by travist** [comment] 2020-09-15 20:40
I believe this is caused by an upgrade to Angular 10. We are working on updating this library to the latest version, but do not have that yet.

**Comment by daneformio** [comment] 2024-01-31 14:54
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-01-31 14:54 UTC
Labels: bug
