### ISSUE TITLE
[WIZARD]: Changing Title of Panel doesn't update BreadCrumb 

### ISSUE THREAD

**Issue by sabinayakc** [formio/angular#458] opened 2020-01-29 22:05 UTC
When I try to change the title of the panel in wizard mode it doesn't update the title until I click on create new page.  I recreated this using the live angular demo application. 

See screenshot video below.
[Angular_Bug_Video.zip](https://github.com/formio/angular-formio/files/4130942/Angular_Bug_Video.zip)

**Comment by travist** [comment] 2020-01-30 15:06
This is probably a bug in the core renderer @ formio/formio.js.  We will add this to our developer backlog, but it seems like it is not a critical item. We may need to ask the help of the community to contribute a fix for this one.

**Comment by Sidiro23** [comment] 2024-02-07 14:29
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-02-07 14:29 UTC
