### ISSUE TITLE
formio hidecomponent attribute to hide fields rendering in Angular 6

### ISSUE THREAD

**Issue by padhumailin** [formio/angular#327] opened 2019-07-12 13:20 UTC
<formio src='https://cjkpltakbutbwzo.form.io/registration' [hideComponents]="hiddenfields"></formio>

passing string array to hidecomponents the fields to be hidden. but not working. How to fix

**Comment by wag110894** [comment] 2019-07-12 17:18
Hello, 
Thanks for reaching out.

We have created a ticket and have added this to our backlog. 

 We will let you when this issue is resolved. 

Thanks.

**Comment by padhumailin** [comment] 2019-07-14 02:40
Is there any way to hide fields in the form in angular 6

**Comment by wag110894** [comment] 2019-07-15 20:25
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested.  Our developers have estimated this fix at 4 hours. 
Please let us know if you are interested and we can send over a formal quote.
 
Thanks.

**Comment by blochealth** [comment] 2020-01-06 21:48
@wag110894, is this implemented? The wiki has documentation for the input [hideComponents], 
but I tried to use it as described here in the code base and I get an error: 

`ERROR Error: "Uncaught (in promise): TypeError: _this.formio.hideComponents is not a function
./node_modules/angular-formio/FormioBaseComponent.js/FormioBaseComponent.prototype.ngOnChanges/<@http://localhost:4200/vendor.js:144022:30
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:10804:26`

**Comment by travist** [comment] 2020-01-13 21:45
It may have been used in the 3.x renderer and was removed in 4.x renderer. We would need to re-introduce this to the renderer. It is probably not going to become a high priority item since we are tied up with other things. Maybe someone from the community can contribute to this fix?

**Comment by blochealth** [comment] 2020-06-01 17:08
Note this is a duplicate of #243

**Comment by daneformio** [comment] 2024-01-31 14:48
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-01-31 14:48 UTC
