### ISSUE TITLE
Sub form(nested form) data object contains parent data also.

### ISSUE THREAD

**Issue by shai93** [formio/angular#296] opened 2019-05-20 12:06 UTC
In the nested form after submitting parent form the subform data object contains parent data also which get added on every submits action of the parent form
Is there any way to get only subform data on submitting the parent form?

**Comment by wag110894** [comment] 2019-05-20 14:27
Can you please provide an example or screencast of this issue? This will help us be able to reproduce this issue.

Thanks.

**Comment by shai93** [comment] 2019-05-21 06:45
Example: - 
`{
  "data": {
    "body": "",
    "actionlinks": true,
    "apiformdetails": {
      "data": {
        "querytype": {
          "query": false,
          "mutation": false
        },
        "body": "",
        "actionlinks": true,
        "apiformdetails": {},
        "path": "table/list",
        "colheaders": "",
        "headers": [
          {
            "headerkey": "",
            "headervalue": ""
          }
        ],
        "query": "",
        "requesttype": "apiRequest",
        "mutation": "",
        "groupbykey": "",
        "apiheaders": {
          "headers": false,
          "body": false
        },
        "updatedAt": "2019-05-17T12:10:31.117Z",
        "datapath": "",
        "responsive": false,
        "colresize": true,
        "toggle": false,
        "apiurl": "dsdas",
        "__v": 0,
        "groupby": false,
        "submit": true,
        "title": "Table list",
        "actionurls": {
          "addurl": "http://127.0.0.1:4200/table/create",
          "editurl": "http://127.0.0.1:4200/table/{_id}/edit",
          "viewurl": "http://127.0.0.1:4200/table/{_id}/preview",
          "deleteurl": "http://127.0.0.1:4200/table/{_id}/delete"
        },
        "pagination": {
          "active": true,
          "rows": "10"
        },
        "globalfilter": true,
        "createdAt": "2019-05-02T12:11:34.571Z",
        "colfilters": true,
        "apimethod": "get",
        "bodytype": "",
        "customheader": [
          {
            "api_key": "title",
            "cols": "Title",
            "headerfilter": true
          },
          {
            "api_key": "path",
            "cols": "Path",
            "headerfilter": true
          },
          {
            "api_key": "dataapi",
            "cols": "Data API",
            "headerfilter": true
          }
        ],
        "sort": true
      },
      "metadata": {}
    },
    "path": "table/list",
    "colheaders": "",
    "query": "",
    "requesttype": "apiRequest",
    "mutation": "",
    "groupbykey": "",
    "apiheaders": {
      "headers": false,
      "body": false
    },
    "updatedAt": "2019-05-20T08:44:41.709Z",
    "datapath": "",
    "responsive": false,
    "colresize": true,
    "toggle": false,
    "apiurl": "dsdas",
    "__v": 0,
    "groupby": false,
    "submit": true,
    "title": "Table list",
    "actionurls": {
      "addurl": "http://127.0.0.1:4200/table/create",
      "editurl": "http://127.0.0.1:4200/table/{_id}/edit",
      "viewurl": "http://127.0.0.1:4200/table/{_id}/preview",
      "deleteurl": "http://127.0.0.1:4200/table/{_id}/delete"
    },
    "pagination": {
      "active": true,
      "rows": "10"
    },
    "globalfilter": true,
    "createdAt": "2019-05-02T12:11:34.571Z",
    "colfilters": true,
    "apimethod": "get",
    "customheader": [
      {
        "api_key": "title",
        "cols": "Title",
        "headerfilter": true
      },
      {
        "api_key": "path",
        "cols": "Path",
        "headerfilter": true
      },
      {
        "api_key": "dataapi",
        "cols": "Data API",
        "headerfilter": true
      }
    ],
    "sort": true
  },
  "metadata": {}
}`

the data object is parent object and apiformdetails key is subform data which contains child form fields along with parent fields and also on every saves the parent data gets added to the nested form.
Also, save as reference option not giving child form _id

**Comment by shai93** [comment] 2019-05-21 06:56
Example: -
{
	"data": {
		"body": "",
		"actionlinks": true,
		"apiformdetails": {
			"data": {
				"querytype": {
					"query": false,
					"mutation": false
				},
				"body": "",
				"actionlinks": true,
				"apiformdetails": {},
				"path": "table/list",
				"colheaders": "",
				"headers": [{
					"headerkey": "",
					"headervalue": ""
				}],
				"query": "",
				"requesttype": "apiRequest",
				"mutation": "",
				"groupbykey": "",
				"apiheaders": {
					"headers": false,
					"body": false
				},
				"updatedAt": "2019-05-17T12:10:31.117Z",
				"datapath": "",
				"responsive": false,
				"colresize": true,
				"toggle": false,
				"apiurl": "mycustomurl",
				"__v": 0,
				"groupby": false,
				"submit": true,
				"title": "Table list",
				"actionurls": {
					"addurl": "http://127.0.0.1:4200/table/create",
					"editurl": "http://127.0.0.1:4200/table/{_id}/edit",
					"viewurl": "http://127.0.0.1:4200/table/{_id}/preview",
					"deleteurl": "http://127.0.0.1:4200/table/{_id}/delete"
				},
				"pagination": {
					"active": true,
					"rows": "10"
				},
				"globalfilter": true,
				"createdAt": "2019-05-02T12:11:34.571Z",
				"colfilters": true,
				"apimethod": "get",
				"bodytype": "",
				"customheader": [{
						"api_key": "title",
						"cols": "Title",
						"headerfilter": true
					},
					{
						"api_key": "path",
						"cols": "Path",
						"headerfilter": true
					},
					{
						"api_key": "dataapi",
						"cols": "Data API",
						"headerfilter": true
					}
				],
				"sort": true
			},
			"metadata": {}
		},
		"path": "table/list",
		"colheaders": "",
		"query": "",
		"requesttype": "apiRequest",
		"mutation": "",
		"groupbykey": "",
		"apiheaders": {
			"headers": false,
			"body": false
		},
		"updatedAt": "2019-05-20T08:44:41.709Z",
		"datapath": "",
		"responsive": false,
		"colresize": true,
		"toggle": false,
		"apiurl": "mycustomurl",
		"__v": 0,
		"groupby": false,
		"submit": true,
		"title": "Table list",
		"actionurls": {
			"addurl": "http://127.0.0.1:4200/table/create",
			"editurl": "http://127.0.0.1:4200/table/{_id}/edit",
			"viewurl": "http://127.0.0.1:4200/table/{_id}/preview",
			"deleteurl": "http://127.0.0.1:4200/table/{_id}/delete"
		},
		"pagination": {
			"active": true,
			"rows": "10"
		},
		"globalfilter": true,
		"createdAt": "2019-05-02T12:11:34.571Z",
		"colfilters": true,
		"apimethod": "get",
		"customheader": [{
				"api_key": "title",
				"cols": "Title",
				"headerfilter": true
			},
			{
				"api_key": "path",
				"cols": "Path",
				"headerfilter": true
			},
			{
				"api_key": "dataapi",
				"cols": "Data API",
				"headerfilter": true
			}
		],
		"sort": true
	},
	"metadata": {}
}

The data object is parent object and apiformdetails key is subform data which contains child form fields along with parent fields and also on every saves the parent data gets added to the nested form.
Also, save as reference option not giving child form _id

**Comment by travist** [comment] 2019-05-22 20:41
This should only occur if you have "Save as Reference" unchecked for that form component. If you check that value, it should save a "reference" to the subform submission which will not include the data. Please verify if that works.

**Comment by franke-mc** [comment] 2019-05-28 13:44
@travist: not sure if (still) relevant, but recently we found that "Save as Reference" MUST BE unchecked in any nested form. Otherwise, input values of the inner forms wouldn't reach the server at all. (originally observed on formio.js derived from 3.19.4)

**Comment by travist** [comment] 2019-05-28 20:43
The Save as Reference with nested forms should work as follows.
 - Checked:  The nested form will save the submission to the subform, then take the result and only populate the "_id" of the nested submission to the parent submission object. Then when the form is loaded, it will lazy-load the sub-submission into the nested form.
 - Unchecked: The nested form just behaves like a nested form and the data that is collected is not sent to the subform endpoint but rather just saved as nested data to the parent submission object.

Will you confirm that is how it is behaving?

**Comment by franke-mc** [comment] 2019-05-29 13:36
I have tested this in two setups:
- on beta.form.io, and 
- patched angular-app-starterkit /#/form on a docker-compose setup from formio:
[angular-app-starterkit.diff.txt](https://github.com/formio/angular-formio/files/3232727/angular-app-starterkit.diff.txt)

Results:
- Unchecked is working as advertised everywhere.
- Checked is working as advertised on beta.form.io. But it is not working with formio3: there is only a single POST to the outer form, with an empty data.nestedForm = {}.
![NestedForm_SaveAsReferenceON formio3](https://user-images.githubusercontent.com/46748541/58561480-7a60a400-8227-11e9-8ddb-d8958d119880.png)

Additional observations:
- Only on beta.form.io, after the POST requests, there are some additional PUT requests.
- The label given in the Nested Form component is never displayed (even if "Hide Label" is off).

**Comment by travist** [comment] 2019-05-30 15:09
The additional PUT requests happens because the sub-submissions are saved and are updated when the final form is submitted. What do you mean by "formio3"? 

As for the label, I don't believe the label should have ever been shown so I don't believe that is a bug.

That being said... I am still not completely clear what is actually a "bug" here. If it works in https://beta.form.io then this tells me that the core renderer does work as it should. In what context are you seeing problems?

**Comment by franke-mc** [comment] 2019-05-31 09:01
The "bug" is #299 which I had not yet seen when I started commenting here:
- "On form submission does not collect filled fields values from form`s subforms"
In particular, note the data: { ... nestedForm: {} ...} in the single POST to submission of the outer form.
There are NO other post requests, the one to the inner form is missing.

The context is the other setup I mentioned:
- Go to /#/form on an angular-app-starterkit running against the api from a docker-compose setup from formio/formio:
  [angular-app-starterkit.diff.txt](https://github.com/formio/angular-formio/files/3232727/angular-app-starterkit.diff.txt)
But I am observing the same on any version of our customized setup, currently derived from angular-formio:3.16.2 and formiojs:3.20.17 (all pre-4.x.x-beta, thus "formio3"); the above configuration was chosen only because it does not contain our customizations and should be easy to reproduce. It does NOT occur on portal.form.io currently, though. (Which version is that?)

**Comment by travist** [comment] 2019-05-31 14:41
We will need to get a reproducible case to fix this on our end. That may take some time unless someone provides a JSFiddle showing the problem. Regardless, we will assign this to our backlog and discuss it in our Monday planning meeting.

portal.form.io uses our Angular 1.x 2.x renderer/builder so that is really old and is a completely different implementation. If you want to see our Core renderer (3.x) version of our portal.form.io, then go to https://beta.form.io. Does this reproduce there?

**Comment by franke-mc** [comment] 2019-06-03 11:06
@travist: As stated above, it does not reproduce on beta.form.io . But here is a script automating the setup to reproduce this (rename from .sh.txt to txt): 
[formio-nested-form-save-as-reference.sh.txt](https://github.com/formio/angular-formio/files/3247228/formio-nested-form-save-as-reference.sh.txt)
Hope this helps...

**Comment by franke-mc** [comment] 2019-06-03 13:56
With improved shutdown instructions: 
[formio-nested-form-save-as-reference.sh.txt](https://github.com/formio/angular-formio/files/3247889/formio-nested-form-save-as-reference.sh.txt)

**Comment by travist** [comment] 2019-06-03 14:34
Thanks for the detailed reproducible script. This will take some time to digest and we will need to allocate a developer to look into it. As of now, our developers are tied up with other projects. I will make sure we add this to our backlog in our planning sessions today.

**Comment by wag110894** [comment] 2019-06-03 15:44
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by franke-mc** [comment] 2019-06-05 10:54
Additional observations:
- The above problem occurs on both angular-app-starterkit and angular-demo.
- It is not specific to angular-formio. It can be observed in react-formio as well:
- (1) With react-app-starterkit using react-formio 3.1.12 and formiojs 3.17.4, nestedForm is not empty but contains an empty data:{text:""}.
- (2) With formiojs 3.21.3, we observe an empty nestedForm again.
- (3) With current react-formio 4.0.0-beta.22 and formiojs 4.0.0-beta.41, it's the same as in (1).
Note: For these versions to work, CheckMatrix needs to be removed from src/components.
Overall, it looks like 4.0.0-beta.* is not up to date with 3.x fixes.

**Comment by franke-mc** [comment] 2019-06-05 16:06
I spoke too soon....

In 3.x, after these commits:
- [Fixing the subform loading/saving to only use the 'reference' variable for consistency.](https://github.com/formio/formio.js/commit/6ef89bcebc656cdc18fc9586e053883bcfd2d2ab#diff-6119202d411fd338dd5fb91eea8f5078)
- [Fixed issues with the subform setting data.](https://github.com/formio/formio.js/commit/2541cf6d8d4353d2d34f82b8fbc8dfaaa6df7c4e#diff-e1a325f3b81917542c3b6e233104e843)
there appear to be two problems:
1. In case of `"reference": true`, the `submission.data` of the subform holds just a skeleton `{ text: "" }` instead of the full `{ text: "something" }` 
2. In case of `"reference": true`, nosubmit always stays true on the subform even though shouldSubmit is true as well.  At some point, [`submitForm()` is indeed called on the subform](https://github.com/formio/formio.js/blob/master/src/components/form/Form.js#L346), but since that call returns early because of nosubmit = true, both _id and form are undefined. setValue is called multiple times, but never with a [submission._id](https://github.com/formio/formio.js/blob/master/src/components/form/Form.js#L387) that would have triggered a `setUrl` followed by a `.nosubmit = false` assignment.

In 4.x, there is this commit:
[Fix bug with nosubmit flag for nested forms](https://github.com/formio/formio.js/commit/9fa74b35dd68a4a7bf7f23eb0414e090e50583fc#diff-e1a325f3b81917542c3b6e233104e843)
Why is this only in 4.x and not in 3.x?

**Comment by franke-mc** [comment] 2019-06-05 17:12
Adding the above line in 3.x fixes the issue for me; I'm going to make a pull request.

**Comment by travist** [comment] 2019-06-05 21:46
The code that was introduced in 3.x to supposedly solve the nested form problem was never ported to 4.x (yet), so we need to look at 3.x as the current "way" it is done until that is ported. From your point, it does appear there is a problem, but I am still confused why beta.form.io portal works according to design which should be as follows.

 - Form component with Save as Reference checked:  Should submit the subform, and then set only {_id: [SUBMISSION_ID]} as the value of the form component.
 - Form component with Save as Reference unchecked: Should not submit the subform, but set the values of the data to the nested form to be submitted along with the parent form. 

I was pretty sure this was tested to work in the 3.x renderer. I am hearing from you otherwise, so we will just need to kick this back to a developer on our end to fix. We are currently swamped so I don't see this happening soon. I took a look at your pull request and unfortunately we probably won't be able to accept that. It will take more investigation.

**Comment by franke-mc** [comment] 2019-06-06 12:44
Ok, that's fine.

Actually, on beta.form.io it does not fully work. (It would be nice to have a way to correlate the formio.js versions on {beta,portal}.form.io with github commits or tags.)

1. The initial POST to the inner form is alright:  {"data":{"text":"aabb"}...}
2. The subsequent POST to the outer form looks good, too: 
  `{"data":{"nestedForm":{"_id":"5cf9056bb0c7baf39f79c3f9",
  "form":"5cee4ae6a039cee4c6627027"},"number2":1122...}...}`
3. But then, in two subsequent PUT requests to the outer (!, not inner) form submission,
   the behaviour is as if 'reference' was false:
  `{"data":{"nestedForm":{"data":{"text":"aabb"},"_id":"5cf9056bb0c7baf39f79c3f9","form":"5cee4ae6a039cee4c6627027"},
"number2":1122...},"form":"5cee4b70a039ce39b0627036"...}`
4. In the final GET request for the outer form submission, the response contains nestedForm with correct _id and form, but also an empty data: {}, causing the subform value not to be displayed.

**Comment by daneformio** [comment] 2024-01-31 14:51
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-01-31 14:51 UTC
