### ISSUE TITLE
[BUG] FormBuilder is now showing up

### ISSUE THREAD

**Issue by chengzhao41** [formio/angular#406] opened 2019-11-15 19:57 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.3.1
- Frontend framework: Angular 8
- Browser: Chrome
- Browser version: 78

## Steps to Reproduce
Please see https://stackoverflow.com/questions/58869228/formio-formbuilder-not-showing-in-angular-8 

Also if I only put 1 form builder, the final HTML only shows an empty FormBuilder tag http://screen/QZbEbgDfsos

## Expected behavior
Form Builder shows up

## Observed behavior
Form Builder is in the HTML but not visible.

**Comment by zwjohn** [comment] 2019-11-20 16:38
If you downgrade angular-formio to 3.27.1 in your package.json, the builder should render. It seems angular version upgrade in 4.0 caused this issue, builder stopped rendering from 4.0 to the latest version. I was wondering why no one reported this issue for so long....

**Comment by merobal** [comment] 2019-11-21 12:35
Can you please provide a small repro? I can't reproduce this with clean install.

**Comment by Sidiro23** [comment] 2024-02-07 14:19
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by Sidiro23** 2024-02-07 14:19 UTC
Labels: repro needed
